// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/video_service.proto

package video

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,5,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,6,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Duration      int32                  `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	ViewCount     int64                  `protobuf:"varint,8,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount     int64                  `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ShareCount    int64                  `protobuf:"varint,10,opt,name=share_count,json=shareCount,proto3" json:"share_count,omitempty"`
	IsPublic      bool                   `protobuf:"varint,11,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_proto_video_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{0}
}

func (x *Video) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Video) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Video) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *Video) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Video) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Video) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Video) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Video) GetShareCount() int64 {
	if x != nil {
		return x.ShareCount
	}
	return 0
}

func (x *Video) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Video) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Video) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VideoUrl      string                 `protobuf:"bytes,4,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,5,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	Duration      int32                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	IsPublic      bool                   `protobuf:"varint,7,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoRequest) Reset() {
	*x = CreateVideoRequest{}
	mi := &file_proto_video_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoRequest) ProtoMessage() {}

func (x *CreateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoRequest.ProtoReflect.Descriptor instead.
func (*CreateVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVideoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateVideoRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *CreateVideoRequest) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *CreateVideoRequest) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *CreateVideoRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type CreateVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *Video                 `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVideoResponse) Reset() {
	*x = CreateVideoResponse{}
	mi := &file_proto_video_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVideoResponse) ProtoMessage() {}

func (x *CreateVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVideoResponse.ProtoReflect.Descriptor instead.
func (*CreateVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVideoResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

type GetVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoRequest) Reset() {
	*x = GetVideoRequest{}
	mi := &file_proto_video_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoRequest) ProtoMessage() {}

func (x *GetVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoRequest.ProtoReflect.Descriptor instead.
func (*GetVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetVideoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *Video                 `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoResponse) Reset() {
	*x = GetVideoResponse{}
	mi := &file_proto_video_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoResponse) ProtoMessage() {}

func (x *GetVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoResponse.ProtoReflect.Descriptor instead.
func (*GetVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetVideoResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

type ListVideosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosRequest) Reset() {
	*x = ListVideosRequest{}
	mi := &file_proto_video_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosRequest) ProtoMessage() {}

func (x *ListVideosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosRequest.ProtoReflect.Descriptor instead.
func (*ListVideosRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListVideosRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVideosRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListVideosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVideosResponse) Reset() {
	*x = ListVideosResponse{}
	mi := &file_proto_video_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVideosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVideosResponse) ProtoMessage() {}

func (x *ListVideosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVideosResponse.ProtoReflect.Descriptor instead.
func (*ListVideosResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListVideosResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *ListVideosResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetVideosByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideosByUserRequest) Reset() {
	*x = GetVideosByUserRequest{}
	mi := &file_proto_video_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosByUserRequest) ProtoMessage() {}

func (x *GetVideosByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosByUserRequest.ProtoReflect.Descriptor instead.
func (*GetVideosByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetVideosByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetVideosByUserRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetVideosByUserRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetVideosByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*Video               `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideosByUserResponse) Reset() {
	*x = GetVideosByUserResponse{}
	mi := &file_proto_video_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideosByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideosByUserResponse) ProtoMessage() {}

func (x *GetVideosByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideosByUserResponse.ProtoReflect.Descriptor instead.
func (*GetVideosByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetVideosByUserResponse) GetVideos() []*Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *GetVideosByUserResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,4,opt,name=thumbnail_url,json=thumbnailUrl,proto3" json:"thumbnail_url,omitempty"`
	IsPublic      bool                   `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3" json:"is_public,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoRequest) Reset() {
	*x = UpdateVideoRequest{}
	mi := &file_proto_video_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoRequest) ProtoMessage() {}

func (x *UpdateVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoRequest.ProtoReflect.Descriptor instead.
func (*UpdateVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateVideoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateVideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateVideoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateVideoRequest) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *UpdateVideoRequest) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type UpdateVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Video         *Video                 `protobuf:"bytes,1,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVideoResponse) Reset() {
	*x = UpdateVideoResponse{}
	mi := &file_proto_video_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVideoResponse) ProtoMessage() {}

func (x *UpdateVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVideoResponse.ProtoReflect.Descriptor instead.
func (*UpdateVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateVideoResponse) GetVideo() *Video {
	if x != nil {
		return x.Video
	}
	return nil
}

type DeleteVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoRequest) Reset() {
	*x = DeleteVideoRequest{}
	mi := &file_proto_video_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoRequest) ProtoMessage() {}

func (x *DeleteVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoRequest.ProtoReflect.Descriptor instead.
func (*DeleteVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteVideoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVideoResponse) Reset() {
	*x = DeleteVideoResponse{}
	mi := &file_proto_video_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVideoResponse) ProtoMessage() {}

func (x *DeleteVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVideoResponse.ProtoReflect.Descriptor instead.
func (*DeleteVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type LikeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoRequest) Reset() {
	*x = LikeVideoRequest{}
	mi := &file_proto_video_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoRequest) ProtoMessage() {}

func (x *LikeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoRequest.ProtoReflect.Descriptor instead.
func (*LikeVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{13}
}

func (x *LikeVideoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LikeVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type LikeVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LikeCount     int64                  `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeVideoResponse) Reset() {
	*x = LikeVideoResponse{}
	mi := &file_proto_video_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeVideoResponse) ProtoMessage() {}

func (x *LikeVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeVideoResponse.ProtoReflect.Descriptor instead.
func (*LikeVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{14}
}

func (x *LikeVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LikeVideoResponse) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type UnlikeVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeVideoRequest) Reset() {
	*x = UnlikeVideoRequest{}
	mi := &file_proto_video_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeVideoRequest) ProtoMessage() {}

func (x *UnlikeVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeVideoRequest.ProtoReflect.Descriptor instead.
func (*UnlikeVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{15}
}

func (x *UnlikeVideoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnlikeVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type UnlikeVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	LikeCount     int64                  `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeVideoResponse) Reset() {
	*x = UnlikeVideoResponse{}
	mi := &file_proto_video_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeVideoResponse) ProtoMessage() {}

func (x *UnlikeVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeVideoResponse.ProtoReflect.Descriptor instead.
func (*UnlikeVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{16}
}

func (x *UnlikeVideoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlikeVideoResponse) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type CheckUserLikedVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserLikedVideoRequest) Reset() {
	*x = CheckUserLikedVideoRequest{}
	mi := &file_proto_video_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserLikedVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserLikedVideoRequest) ProtoMessage() {}

func (x *CheckUserLikedVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserLikedVideoRequest.ProtoReflect.Descriptor instead.
func (*CheckUserLikedVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{17}
}

func (x *CheckUserLikedVideoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckUserLikedVideoRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type CheckUserLikedVideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsLiked       bool                   `protobuf:"varint,1,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserLikedVideoResponse) Reset() {
	*x = CheckUserLikedVideoResponse{}
	mi := &file_proto_video_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserLikedVideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserLikedVideoResponse) ProtoMessage() {}

func (x *CheckUserLikedVideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserLikedVideoResponse.ProtoReflect.Descriptor instead.
func (*CheckUserLikedVideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{18}
}

func (x *CheckUserLikedVideoResponse) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

type GetVideoLikeCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoLikeCountRequest) Reset() {
	*x = GetVideoLikeCountRequest{}
	mi := &file_proto_video_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoLikeCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoLikeCountRequest) ProtoMessage() {}

func (x *GetVideoLikeCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoLikeCountRequest.ProtoReflect.Descriptor instead.
func (*GetVideoLikeCountRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetVideoLikeCountRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type GetVideoLikeCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LikeCount     int64                  `protobuf:"varint,1,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVideoLikeCountResponse) Reset() {
	*x = GetVideoLikeCountResponse{}
	mi := &file_proto_video_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVideoLikeCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoLikeCountResponse) ProtoMessage() {}

func (x *GetVideoLikeCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoLikeCountResponse.ProtoReflect.Descriptor instead.
func (*GetVideoLikeCountResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetVideoLikeCountResponse) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type CreateViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VideoId       string                 `protobuf:"bytes,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	WatchTime     int32                  `protobuf:"varint,3,opt,name=watch_time,json=watchTime,proto3" json:"watch_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateViewRequest) Reset() {
	*x = CreateViewRequest{}
	mi := &file_proto_video_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateViewRequest) ProtoMessage() {}

func (x *CreateViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateViewRequest.ProtoReflect.Descriptor instead.
func (*CreateViewRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{21}
}

func (x *CreateViewRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateViewRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *CreateViewRequest) GetWatchTime() int32 {
	if x != nil {
		return x.WatchTime
	}
	return 0
}

type CreateViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TotalViews    int64                  `protobuf:"varint,2,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateViewResponse) Reset() {
	*x = CreateViewResponse{}
	mi := &file_proto_video_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateViewResponse) ProtoMessage() {}

func (x *CreateViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateViewResponse.ProtoReflect.Descriptor instead.
func (*CreateViewResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_service_proto_rawDescGZIP(), []int{22}
}

func (x *CreateViewResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateViewResponse) GetTotalViews() int64 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

var File_proto_video_service_proto protoreflect.FileDescriptor

const file_proto_video_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/video_service.proto\x12\x05video\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x03\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tvideo_url\x18\x05 \x01(\tR\bvideoUrl\x12#\n" +
	"\rthumbnail_url\x18\x06 \x01(\tR\fthumbnailUrl\x12\x1a\n" +
	"\bduration\x18\a \x01(\x05R\bduration\x12\x1d\n" +
	"\n" +
	"view_count\x18\b \x01(\x03R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\x03R\tlikeCount\x12\x1f\n" +
	"\vshare_count\x18\n" +
	" \x01(\x03R\n" +
	"shareCount\x12\x1b\n" +
	"\tis_public\x18\v \x01(\bR\bisPublic\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe0\x01\n" +
	"\x12CreateVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tvideo_url\x18\x04 \x01(\tR\bvideoUrl\x12#\n" +
	"\rthumbnail_url\x18\x05 \x01(\tR\fthumbnailUrl\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x05R\bduration\x12\x1b\n" +
	"\tis_public\x18\a \x01(\bR\bisPublic\"9\n" +
	"\x13CreateVideoResponse\x12\"\n" +
	"\x05video\x18\x01 \x01(\v2\f.video.VideoR\x05video\"!\n" +
	"\x0fGetVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x10GetVideoResponse\x12\"\n" +
	"\x05video\x18\x01 \x01(\v2\f.video.VideoR\x05video\"A\n" +
	"\x11ListVideosRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"P\n" +
	"\x12ListVideosResponse\x12$\n" +
	"\x06videos\x18\x01 \x03(\v2\f.video.VideoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"_\n" +
	"\x16GetVideosByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"U\n" +
	"\x17GetVideosByUserResponse\x12$\n" +
	"\x06videos\x18\x01 \x03(\v2\f.video.VideoR\x06videos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x9e\x01\n" +
	"\x12UpdateVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rthumbnail_url\x18\x04 \x01(\tR\fthumbnailUrl\x12\x1b\n" +
	"\tis_public\x18\x05 \x01(\bR\bisPublic\"9\n" +
	"\x13UpdateVideoResponse\x12\"\n" +
	"\x05video\x18\x01 \x01(\v2\f.video.VideoR\x05video\"$\n" +
	"\x12DeleteVideoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13DeleteVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"F\n" +
	"\x10LikeVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\"L\n" +
	"\x11LikeVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x03R\tlikeCount\"H\n" +
	"\x12UnlikeVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\"N\n" +
	"\x13UnlikeVideoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x03R\tlikeCount\"P\n" +
	"\x1aCheckUserLikedVideoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\"8\n" +
	"\x1bCheckUserLikedVideoResponse\x12\x19\n" +
	"\bis_liked\x18\x01 \x01(\bR\aisLiked\"5\n" +
	"\x18GetVideoLikeCountRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\":\n" +
	"\x19GetVideoLikeCountResponse\x12\x1d\n" +
	"\n" +
	"like_count\x18\x01 \x01(\x03R\tlikeCount\"f\n" +
	"\x11CreateViewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\tR\avideoId\x12\x1d\n" +
	"\n" +
	"watch_time\x18\x03 \x01(\x05R\twatchTime\"O\n" +
	"\x12CreateViewResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vtotal_views\x18\x02 \x01(\x03R\n" +
	"totalViews2\xb1\x06\n" +
	"\fVideoService\x12D\n" +
	"\vCreateVideo\x12\x19.video.CreateVideoRequest\x1a\x1a.video.CreateVideoResponse\x12;\n" +
	"\bGetVideo\x12\x16.video.GetVideoRequest\x1a\x17.video.GetVideoResponse\x12A\n" +
	"\n" +
	"ListVideos\x12\x18.video.ListVideosRequest\x1a\x19.video.ListVideosResponse\x12P\n" +
	"\x0fGetVideosByUser\x12\x1d.video.GetVideosByUserRequest\x1a\x1e.video.GetVideosByUserResponse\x12D\n" +
	"\vUpdateVideo\x12\x19.video.UpdateVideoRequest\x1a\x1a.video.UpdateVideoResponse\x12D\n" +
	"\vDeleteVideo\x12\x19.video.DeleteVideoRequest\x1a\x1a.video.DeleteVideoResponse\x12>\n" +
	"\tLikeVideo\x12\x17.video.LikeVideoRequest\x1a\x18.video.LikeVideoResponse\x12D\n" +
	"\vUnlikeVideo\x12\x19.video.UnlikeVideoRequest\x1a\x1a.video.UnlikeVideoResponse\x12\\\n" +
	"\x13CheckUserLikedVideo\x12!.video.CheckUserLikedVideoRequest\x1a\".video.CheckUserLikedVideoResponse\x12V\n" +
	"\x11GetVideoLikeCount\x12\x1f.video.GetVideoLikeCountRequest\x1a .video.GetVideoLikeCountResponse\x12A\n" +
	"\n" +
	"CreateView\x12\x18.video.CreateViewRequest\x1a\x19.video.CreateViewResponseB\x1bZ\x19video-service/proto/videob\x06proto3"

var (
	file_proto_video_service_proto_rawDescOnce sync.Once
	file_proto_video_service_proto_rawDescData []byte
)

func file_proto_video_service_proto_rawDescGZIP() []byte {
	file_proto_video_service_proto_rawDescOnce.Do(func() {
		file_proto_video_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_video_service_proto_rawDesc), len(file_proto_video_service_proto_rawDesc)))
	})
	return file_proto_video_service_proto_rawDescData
}

var file_proto_video_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_video_service_proto_goTypes = []any{
	(*Video)(nil),                       // 0: video.Video
	(*CreateVideoRequest)(nil),          // 1: video.CreateVideoRequest
	(*CreateVideoResponse)(nil),         // 2: video.CreateVideoResponse
	(*GetVideoRequest)(nil),             // 3: video.GetVideoRequest
	(*GetVideoResponse)(nil),            // 4: video.GetVideoResponse
	(*ListVideosRequest)(nil),           // 5: video.ListVideosRequest
	(*ListVideosResponse)(nil),          // 6: video.ListVideosResponse
	(*GetVideosByUserRequest)(nil),      // 7: video.GetVideosByUserRequest
	(*GetVideosByUserResponse)(nil),     // 8: video.GetVideosByUserResponse
	(*UpdateVideoRequest)(nil),          // 9: video.UpdateVideoRequest
	(*UpdateVideoResponse)(nil),         // 10: video.UpdateVideoResponse
	(*DeleteVideoRequest)(nil),          // 11: video.DeleteVideoRequest
	(*DeleteVideoResponse)(nil),         // 12: video.DeleteVideoResponse
	(*LikeVideoRequest)(nil),            // 13: video.LikeVideoRequest
	(*LikeVideoResponse)(nil),           // 14: video.LikeVideoResponse
	(*UnlikeVideoRequest)(nil),          // 15: video.UnlikeVideoRequest
	(*UnlikeVideoResponse)(nil),         // 16: video.UnlikeVideoResponse
	(*CheckUserLikedVideoRequest)(nil),  // 17: video.CheckUserLikedVideoRequest
	(*CheckUserLikedVideoResponse)(nil), // 18: video.CheckUserLikedVideoResponse
	(*GetVideoLikeCountRequest)(nil),    // 19: video.GetVideoLikeCountRequest
	(*GetVideoLikeCountResponse)(nil),   // 20: video.GetVideoLikeCountResponse
	(*CreateViewRequest)(nil),           // 21: video.CreateViewRequest
	(*CreateViewResponse)(nil),          // 22: video.CreateViewResponse
	(*timestamppb.Timestamp)(nil),       // 23: google.protobuf.Timestamp
}
var file_proto_video_service_proto_depIdxs = []int32{
	23, // 0: video.Video.created_at:type_name -> google.protobuf.Timestamp
	23, // 1: video.Video.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: video.CreateVideoResponse.video:type_name -> video.Video
	0,  // 3: video.GetVideoResponse.video:type_name -> video.Video
	0,  // 4: video.ListVideosResponse.videos:type_name -> video.Video
	0,  // 5: video.GetVideosByUserResponse.videos:type_name -> video.Video
	0,  // 6: video.UpdateVideoResponse.video:type_name -> video.Video
	1,  // 7: video.VideoService.CreateVideo:input_type -> video.CreateVideoRequest
	3,  // 8: video.VideoService.GetVideo:input_type -> video.GetVideoRequest
	5,  // 9: video.VideoService.ListVideos:input_type -> video.ListVideosRequest
	7,  // 10: video.VideoService.GetVideosByUser:input_type -> video.GetVideosByUserRequest
	9,  // 11: video.VideoService.UpdateVideo:input_type -> video.UpdateVideoRequest
	11, // 12: video.VideoService.DeleteVideo:input_type -> video.DeleteVideoRequest
	13, // 13: video.VideoService.LikeVideo:input_type -> video.LikeVideoRequest
	15, // 14: video.VideoService.UnlikeVideo:input_type -> video.UnlikeVideoRequest
	17, // 15: video.VideoService.CheckUserLikedVideo:input_type -> video.CheckUserLikedVideoRequest
	19, // 16: video.VideoService.GetVideoLikeCount:input_type -> video.GetVideoLikeCountRequest
	21, // 17: video.VideoService.CreateView:input_type -> video.CreateViewRequest
	2,  // 18: video.VideoService.CreateVideo:output_type -> video.CreateVideoResponse
	4,  // 19: video.VideoService.GetVideo:output_type -> video.GetVideoResponse
	6,  // 20: video.VideoService.ListVideos:output_type -> video.ListVideosResponse
	8,  // 21: video.VideoService.GetVideosByUser:output_type -> video.GetVideosByUserResponse
	10, // 22: video.VideoService.UpdateVideo:output_type -> video.UpdateVideoResponse
	12, // 23: video.VideoService.DeleteVideo:output_type -> video.DeleteVideoResponse
	14, // 24: video.VideoService.LikeVideo:output_type -> video.LikeVideoResponse
	16, // 25: video.VideoService.UnlikeVideo:output_type -> video.UnlikeVideoResponse
	18, // 26: video.VideoService.CheckUserLikedVideo:output_type -> video.CheckUserLikedVideoResponse
	20, // 27: video.VideoService.GetVideoLikeCount:output_type -> video.GetVideoLikeCountResponse
	22, // 28: video.VideoService.CreateView:output_type -> video.CreateViewResponse
	18, // [18:29] is the sub-list for method output_type
	7,  // [7:18] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_video_service_proto_init() }
func file_proto_video_service_proto_init() {
	if File_proto_video_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_video_service_proto_rawDesc), len(file_proto_video_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_video_service_proto_goTypes,
		DependencyIndexes: file_proto_video_service_proto_depIdxs,
		MessageInfos:      file_proto_video_service_proto_msgTypes,
	}.Build()
	File_proto_video_service_proto = out.File
	file_proto_video_service_proto_goTypes = nil
	file_proto_video_service_proto_depIdxs = nil
}
